# Generated by Django 6.1 on 2026-09-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_commentary_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["created_time"],
                "verbose_name_plural": "commentaries",
            },
        ),
    ]
